# fly.toml file generated for polished-shadow-1893 on 2023-03-28T14:02:21-04:00

app = "polished-shadow-1893"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "den"
processes = []

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
